/*
 * docstore API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@docstore.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.docstore.documentation.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.docstore.documentation.api.model.Environment;
import dev.docstore.documentation.api.model.Space;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Document
 */
@JsonPropertyOrder({
  Document.JSON_PROPERTY_ID,
  Document.JSON_PROPERTY_UUID,
  Document.JSON_PROPERTY_TITLE,
  Document.JSON_PROPERTY_CONTENT,
  Document.JSON_PROPERTY_LATEST_CHANGE,
  Document.JSON_PROPERTY_LATEST_UPDATE,
  Document.JSON_PROPERTY_SPACE,
  Document.JSON_PROPERTY_ENVIRONMENT,
  Document.JSON_PROPERTY_OTHER_ENVIRONMENTS,
  Document.JSON_PROPERTY_TAGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-05-26T07:34:15.178+02:00[Europe/Berlin]")
public class Document {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_UUID = "uuid";
  private String uuid;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private String content;

  public static final String JSON_PROPERTY_LATEST_CHANGE = "latestChange";
  private OffsetDateTime latestChange;

  public static final String JSON_PROPERTY_LATEST_UPDATE = "latestUpdate";
  private OffsetDateTime latestUpdate;

  public static final String JSON_PROPERTY_SPACE = "space";
  private Space space;

  public static final String JSON_PROPERTY_ENVIRONMENT = "environment";
  private Environment environment;

  public static final String JSON_PROPERTY_OTHER_ENVIRONMENTS = "otherEnvironments";
  private List<Environment> otherEnvironments = new ArrayList<>();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<String> tags = new ArrayList<>();


  public Document id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Document uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public Document title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public Document content(String content) {
    
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContent() {
    return content;
  }


  public void setContent(String content) {
    this.content = content;
  }


  public Document latestChange(OffsetDateTime latestChange) {
    
    this.latestChange = latestChange;
    return this;
  }

   /**
   * Get latestChange
   * @return latestChange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LATEST_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLatestChange() {
    return latestChange;
  }


  public void setLatestChange(OffsetDateTime latestChange) {
    this.latestChange = latestChange;
  }


  public Document latestUpdate(OffsetDateTime latestUpdate) {
    
    this.latestUpdate = latestUpdate;
    return this;
  }

   /**
   * Get latestUpdate
   * @return latestUpdate
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LATEST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLatestUpdate() {
    return latestUpdate;
  }


  public void setLatestUpdate(OffsetDateTime latestUpdate) {
    this.latestUpdate = latestUpdate;
  }


  public Document space(Space space) {
    
    this.space = space;
    return this;
  }

   /**
   * Get space
   * @return space
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SPACE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Space getSpace() {
    return space;
  }


  public void setSpace(Space space) {
    this.space = space;
  }


  public Document environment(Environment environment) {
    
    this.environment = environment;
    return this;
  }

   /**
   * Get environment
   * @return environment
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ENVIRONMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Environment getEnvironment() {
    return environment;
  }


  public void setEnvironment(Environment environment) {
    this.environment = environment;
  }


  public Document otherEnvironments(List<Environment> otherEnvironments) {
    
    this.otherEnvironments = otherEnvironments;
    return this;
  }

  public Document addOtherEnvironmentsItem(Environment otherEnvironmentsItem) {
    this.otherEnvironments.add(otherEnvironmentsItem);
    return this;
  }

   /**
   * Get otherEnvironments
   * @return otherEnvironments
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_OTHER_ENVIRONMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Environment> getOtherEnvironments() {
    return otherEnvironments;
  }


  public void setOtherEnvironments(List<Environment> otherEnvironments) {
    this.otherEnvironments = otherEnvironments;
  }


  public Document tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public Document addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return Objects.equals(this.id, document.id) &&
        Objects.equals(this.uuid, document.uuid) &&
        Objects.equals(this.title, document.title) &&
        Objects.equals(this.content, document.content) &&
        Objects.equals(this.latestChange, document.latestChange) &&
        Objects.equals(this.latestUpdate, document.latestUpdate) &&
        Objects.equals(this.space, document.space) &&
        Objects.equals(this.environment, document.environment) &&
        Objects.equals(this.otherEnvironments, document.otherEnvironments) &&
        Objects.equals(this.tags, document.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uuid, title, content, latestChange, latestUpdate, space, environment, otherEnvironments, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    latestChange: ").append(toIndentedString(latestChange)).append("\n");
    sb.append("    latestUpdate: ").append(toIndentedString(latestUpdate)).append("\n");
    sb.append("    space: ").append(toIndentedString(space)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    otherEnvironments: ").append(toIndentedString(otherEnvironments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

